### ISSUE TITLE
Embed padding?

### ISSUE THREAD

**Issue by oliviagrce** [oliviagrce/embed-containers#1]
Hi @muxlowc,

I've been trying to figure this out for an hour but I'm stuck. I watched the videos and I'm using the correct classes: "embed embed-16by9" etc on the Divs and "embed-item" on the svg, but for some reason the padding looks a bit nuts at 320px. I've tried adding a few other classes from Modulifier but nothing is working. Can you help?

Olivia

<img width="963" alt="Screenshot 2020-03-15 at 12 04 43" src="https://user-images.githubusercontent.com/55007072/76705296-66ead080-66b5-11ea-88ba-c82214a705ed.png">
<img width="441" alt="Screenshot 2020-03-15 at 12 05 15" src="https://user-images.githubusercontent.com/55007072/76705298-68b49400-66b5-11ea-9287-2699424aa754.png">

**Comment by muxlowc** [comment]
@oliviagrce I think you may be trying to use svg icons instead of embed..so it should look something more simple like this:

`    <img class="embed-item" src="images/placeholder-4by1.svg" alt="">`

**Comment by oliviagrce** [comment]
It worked!! Thank you!! @muxlowc
